### ISSUE TITLE
Train Question

### ISSUE THREAD

**Issue by chartgod** [ggsDing/SCanNet#17]
Hello.
The following error occurs when running the train_SCD_psd.py file.

[epoch 0] [iter 50 / 297 89.3s] [lr 0.099495] [train seg_loss 2.9487 bn_loss 0.5058 acc 75.97]
[epoch 0] [iter 100 / 297 178.7s] [lr 0.098992] [train seg_loss 2.6328 bn_loss 0.4515 acc 74.73]
[epoch 0] [iter 150 / 297 266.4s] [lr 0.098489] [train seg_loss 2.8728 bn_loss 0.4380 acc 83.67]
[epoch 0] [iter 200 / 297 353.1s] [lr 0.097987] [train seg_loss 2.4735 bn_loss 0.4398 acc 81.03]
[epoch 0] [iter 250 / 297 441.7s] [lr 0.097485] [train seg_loss 2.5351 bn_loss 0.3374 acc 78.55]
Traceback (most recent call last):
  File "train_SCD_psd.py", line 321, in <module>
    main()
  File "train_SCD_psd.py", line 93, in main
    train(train_loader, net, criterion, optimizer, val_loader)
  File "train_SCD_psd.py", line 223, in train
    Fscd_v, mIoU_v, Sek_v, acc_v, loss_v = validate(val_loader, net, criterion, curr_epoch)
  File "train_SCD_psd.py", line 254, in validate
    labels_A = labels_A.squeeze(dim=3)
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

Which part do I need to correct?

**Comment by ggsDing** [comment]
> Hello. The following error occurs when running the train_SCD_psd.py file.
> 
> [epoch 0] [iter 50 / 297 89.3s] [lr 0.099495] [train seg_loss 2.9487 bn_loss 0.5058 acc 75.97] [epoch 0] [iter 100 / 297 178.7s] [lr 0.098992] [train seg_loss 2.6328 bn_loss 0.4515 acc 74.73] [epoch 0] [iter 150 / 297 266.4s] [lr 0.098489] [train seg_loss 2.8728 bn_loss 0.4380 acc 83.67] [epoch 0] [iter 200 / 297 353.1s] [lr 0.097987] [train seg_loss 2.4735 bn_loss 0.4398 acc 81.03] [epoch 0] [iter 250 / 297 441.7s] [lr 0.097485] [train seg_loss 2.5351 bn_loss 0.3374 acc 78.55] Traceback (most recent call last): File "train_SCD_psd.py", line 321, in main() File "train_SCD_psd.py", line 93, in main train(train_loader, net, criterion, optimizer, val_loader) File "train_SCD_psd.py", line 223, in train Fscd_v, mIoU_v, Sek_v, acc_v, loss_v = validate(val_loader, net, criterion, curr_epoch) File "train_SCD_psd.py", line 254, in validate labels_A = labels_A.squeeze(dim=3) IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
> 
> Which part do I need to correct?

Hi. I did not find 'labels_A = labels_A.squeeze(dim=3)' in train_SCD_psd.py. Are you running a previous version?

**Comment by chartgod** [comment]
I've checked the issue. Thank you.
May I ask you an additional question?
When you build the Land-sat dataset, was it built with manual labeling or with tools?
